# Generated by Django 5.2.8 on 2025-11-18 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('avis', models.TextField()),
                ('dateVue', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
