# Generated by Django 5.2.8 on 2025-11-23 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='dateVue',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
