# Generated by Django 5.2.9 on 2026-01-07 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_datevue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIItem',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ed9468c4-ee83-40f4-b419-4e72df94cefa'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
