# Generated by Django 5.2.9 on 2026-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_aiitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
