# Generated by Django 5.2.9 on 2026-01-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_aiitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiitem',
            name='steps',
        ),
    ]
