# Generated by Django 5.2.9 on 2026-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_aiitem_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiitem',
            name='steps',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aiitem',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
