# Generated by Django 5.2.9 on 2026-01-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_aiitem_steps_alter_aiitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiitem',
            name='completed',
        ),
    ]
